#!/bin/bash
ROOT=$(readlink -m $(readlink -f $0)/../../)
MYSQL_HOST=172.16.1.91
D_API=compose_designateapi_1
D_CENTRAL=compose_designatecentral_1
D_MDNS=compose_designatemdns_1
D_PM=compose_designatepoolmanagerbind9_1
D_PM_D=compose_designatepoolmanagerbind9data_1

echo Cleanup...
docker rm -f $(docker ps -a|grep designate|cut -d ' ' -f1 )
docker rmi $(docker images|grep designate|tr -s ' ' ','|cut -d, -f3)
mysql -h ${MYSQL_HOST} -uroot -pkolla -e 'drop database designate'

if [ "$1" == "clean" ]
then
	exit
fi

echo Building...
sh ${ROOT}/docker/designate/designate-base/build --release
sh ${ROOT}/docker/designate/designate-api/build --release
sh ${ROOT}/docker/designate/designate-central/build --release
sh ${ROOT}/docker/designate/designate-mdns/build --release
sh ${ROOT}/docker/designate/designate-poolmanager-bind9/build --release
sh ${ROOT}/docker/designate/designate-poolmanager-bind9-data/build --release

echo Run...
docker-compose -f ${ROOT}/compose/designate.yml up -d

echo Wait...
for c in $D_API $D_CENTRAL $D_MDNS $D_PM $D_PM_D
do
	sleep 5
	docker logs $c
done

